# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b9b601d0ee989983900c76eec012ce9"
name = "Bip Fees"
handle = "bip-fees"
application_url = "https://telephone-mambo-imported-genetics.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://telephone-mambo-imported-genetics.trycloudflare.com/auth/callback", "https://telephone-mambo-imported-genetics.trycloudflare.com/auth/shopify/callback", "https://telephone-mambo-imported-genetics.trycloudflare.com/api/auth/callback"]

[pos]
embedded = true
